/** Task 7 — Expressing Opinions (30s prep / 90s recording). One prompt per test set (1–25). */
export const SPEAKING_TASK7_PROMPTS: string[] = [
  'Do you think companies should make it mandatory for employees to exercise during work hours? Explain your reasons.',
  'Do you think social media platforms should be banned for children under the age of 16? Explain your reasons.',
  'Do you think fast food restaurants should be required to display calorie counts on their menus? Explain your reasons.',
  'Do you think owning a pet should require a license and training certificate? Explain your reasons.',
  'Do you think professional athletes are paid too much compared to teachers and nurses? Explain your reasons.',
  'Do you think schools should replace textbooks entirely with tablets and digital devices? Explain your reasons.',
  'Do you think public transportation in Canadian cities should be made completely free for all residents? Explain your reasons.',
  'Do you think teenagers should be required to do community service before graduating from high school? Explain your reasons.',
  'Do you think it is better to live close to your family or to move to a new city for better opportunities? Explain your reasons.',
  'Do you think the driving learners\' permit in Canada should be raised from 16 to 18? Explain your reasons.',
  'Do you think it is better for a child to learn only one language or multiple languages from an early age? Explain your reasons.',
  'Do you think university education should be free for all citizens, funded entirely by taxpayers? Explain your reasons.',
  'Do you think employers should be allowed to monitor their employees\' emails and online activity at work? Explain your reasons.',
  'Do you think the government should limit the expansion of cities to protect Canadian wildlife, even if it makes housing more expensive? Explain your reasons.',
  'Do you think businesses should be allowed to refuse cash payments and only accept cards or digital transfers? Explain your reasons.',
  'Do you think restaurants in Canada should eliminate tipping and instead pay their staff a higher, guaranteed hourly wage? Explain your reasons.',
  'Should grocery stores be legally prohibited from selling fruits and vegetables wrapped in plastic? Explain your reasons.',
  'Do you think the Canadian government should prioritize funding for high-speed rail between major cities over repairing local highways? Explain your reasons.',
  'Do you think social media influencers have a negative impact on the spending habits of young people? Explain your reasons.',
  'Do you think a four-day work week is more productive for companies than the traditional five-day work week? Explain your reasons.',
  'Do you think Indigenous languages should be taught as a mandatory subject in all Canadian public schools? Explain your reasons.',
  'Should parents be held legally and financially responsible for crimes or vandalism committed by their children under the age of 16? Explain your reasons.',
  'Do you think famous natural landmarks in Canada should limit the number of tourists allowed to visit each year to prevent environmental damage? Explain your reasons.',
  'Do you think fully autonomous (driverless) cars will make our roads safer, or are they too dangerous to be allowed in busy city centers? Explain your reasons.',
  'Do you think the speed limit in all residential areas should be reduced to 30 km/h to increase pedestrian safety? Explain your reasons.',
];
