/** Task 1 — Giving Advice (30s prep / 90s recording). One prompt per test set (1–25). */
export const SPEAKING_TASK1_PROMPTS: string[] = [
  'Your friend, Maya, just moved to a new city for work and is trying to decide whether to rent an apartment alone or find a roommate. Give her your advice on what she should consider before making her decision.',
  'Your co-worker, Sam, has been asked to give a speech at the company\'s annual dinner but he is very nervous about public speaking. Give him your advice on how to prepare and what to keep in mind.',
  'Your 20-year-old cousin, Rizzie, wants to adopt a cat, but she lives in a small studio apartment and works long hours. Give her your advice on whether this is a good idea and what she should think about.',
  'Your neighbour, Paul, is thinking about selling his car and using public transit to save money. Give him your advice on the advantages and disadvantages of each option.',
  'Your friend, Karen, wants to start eating healthier but finds it difficult because she is always busy and relies on fast food. Give her your advice on how she can make better food choices with a busy schedule.',
  'Your brother, Daniel, has been offered two part-time jobs, one at a bookstore and one at a gym. He can only take one. Give him your advice on how he should choose between the two.',
  'Your friend, Emily, is planning her first solo vacation abroad but her parents are worried about her safety. Give her your advice on how to plan a safe trip and reassure her family.',
  'Your co-worker, Kevin, has been asked to switch from the day shift to the night shift with a little higher renumeration at work. He is unsure about it. Give him your advice on what he should consider and whether he should accept the change.',
  'Your friend, Nora, wants to learn how to drive but is afraid of being on the road. Give her your advice on how to overcome her fear and what steps she should take to start learning.',
  'Your 17-year-old nephew, Tyler, is trying to decide whether to go to university abroad or attend a local community college after high school. Give him your advice on what factors he should think about.',
  'Your friend, Aisha, recently got a dog, and it keeps barking loudly at night, disturbing her neighbours. Give her your advice on what she should and should not do to handle the situation.',
  'Your co-worker, Brian, wants to ask his manager for a raise but does not know how to approach the conversation. Give him your advice on how to bring it up.',
  'Your friend, Laura, is thinking about deleting all her social media accounts because she feels it wastes too much of her time. Give her your advice on whether she should quit social media entirely or find a better balance and why.',
  'Your sister, Maria, has been invited to two different weddings on the same weekend where one is of a close friend and the other is a colleague at work. Give her your advice on how she should decide which one to attend.',
  'Your friend, Jason, has just graduated and is wondering whether he should start working immediately or take a few months off to travel. Give him your advice on what he should consider before deciding.',
  'Your neighbour, Mrs. Campbell, wants to plant a vegetable garden in her backyard but has never done any gardening before. Give her your advice on how to get started and what mistakes to avoid.',
  'Your friend, Omar, recently lent a large amount of money to a friend who has not paid him back and keeps avoiding the topic. Give him your advice on how to handle the situation without damaging the friendship.',
  'Your cousin, Sophie, is thinking about changing her university major from business to art in her second year. Her parents are not happy about the idea. Give her your advice on what she should do.',
  'Your co-worker, Anna, has been feeling very tired lately because she stays up late watching television every night. Give her your advice on how to develop a better sleep routine.',
  'Your friend, Tom, wants to organize a surprise birthday party for his wife but has never planned a party before. Give him your advice on what to do and what to avoid when planning the event.',
  'Your friend, Stephie, is nervous because she has a face-to-face job interview next week, and it is her first time appearing for it. Give her your advice on how to prepare and what to expect during the interview.',
  'Your brother, Leo, wants to buy a used car from a private seller he found online. Give him your advice on what to check and what precautions he should take before buying it.',
  'Your friend, Hannah, has been invited to join a weekend hiking group but she has never hiked before and is worried about keeping up with the group. Give her your advice on how to prepare and whether she should go.',
  'Your co-worker, Dave, is thinking about volunteering at a local food bank on weekends but worries he will not have enough free time for himself. Give him your advice on how to balance volunteering with personal time.',
  'Your friend, Rosa, has just moved into a new apartment and is having trouble getting along with her noisy upstairs neighbours. Give her your advice on how she should approach the situation.',
];
